### ISSUE TITLE
Append Fails for multiple appends

### ISSUE THREAD

**Issue by joehand** [mafintosh/hypercore#11]
Trying to do more append at once it fails:

```
/Users/joe/node_modules/dat-examples/node_modules/hypercore/lib/feed.js:125
    for (var i = 0; i < callbacks.length; i++) callbacks[i](err)
                                 ^

TypeError: Cannot read property 'length' of null
    at call (/Users/joe/node_modules/dat-examples/node_modules/hypercore/lib/feed.js:125:34)
    at afterAppend (/Users/joe/node_modules/dat-examples/node_modules/hypercore/lib/feed.js:121:5)
    at /Users/joe/node_modules/dat-examples/node_modules/levelup/lib/levelup.js:320:9
```

Example Script that fails: https://gist.github.com/joehand/137d0b99b42ceba4a6fa

**Comment by mafintosh** [comment]
i think this is fixed. could you try again against latest hypercore?
