### ISSUE TITLE
this.key.read is not a function error when using random-access-memory with hello world example

### ISSUE THREAD

**Issue by aral** [mafintosh/hypercore#160]
## To reproduce

```javascript
const hypercore = require('hypercore')
const ram = require('random-access-memory')

const feed = hypercore((fileName) => { return ram }, {valueEncoding: 'utf-8'})

feed.append('hello')
feed.append('world', (error) => {
  if (error) throw error

  feed.get(0, console.log)
  feed.get(1, console.log)
})
```

## The error

``` bash
  this.key.read(0, 32, cb)
           ^

TypeError: this.key.read is not a function
    at Storage.openKey (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/lib/storage.js:169:12)
    at Storage.openKey (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/lib/storage.js:167:47)
    at Feed._open (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/index.js:192:17)
    at open (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/index.js:107:10)
    at run (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/thunky/index.js:19:5)
    at Feed.thunk [as _ready] (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/thunky/index.js:13:5)
    at new Feed (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/index.js:88:8)
    at Feed (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/node_modules/hypercore/index.js:28:39)
    at Object.<anonymous> (/Users/aral/indie/net/meta/spikes/databases/hypercore-isomorphic/index.js:4:14)
    at Module._compile (module.js:652:30)
```

## Environment

_package.json_ dependencies:

```json
  "dependencies": {
    "hypercore": "^6.15.0",
    "random-access-memory": "^3.0.0"
  }
```

**Comment by aral** [comment]
Also seeing this with `random-access-idb` in the browser. To reproduce, run the following after browserifying it:

```javascript
const hypercore = require('hypercore')
const randomAccessIDB = require('random-access-idb')

const storage = (typeof window === 'undefined') ? './feed' : randomAccessIDB

const feed = hypercore(storage, {valueEncoding: 'utf-8'})

feed.append('hello')
feed.append('world', (error) => {
  if (error) throw error

  feed.get(0, console.log)
  feed.get(1, console.log)
})
```

**Comment by mafintosh** [comment]
You have to instantiate the instance returned. `filename => ram()`

**Comment by aral** [comment]
Ah, thanks, @mafintosh – RTFM apparently doesn’t work if you can’t copy what you see properly 🤦

(I’m making progress with the IDB version. I’ll post the fixed code for that once I have it running too in case anyone else stumbles onto this and then I’ll close the issue.)

**Comment by aral** [comment]
I updated the `random-access-idb` spike to the following and now I’m getting a new error (_Error: No node found_) when I try a `get()`. Found this IRC conversation (https://botbot.me/freenode/dat/2017-06-23/?msg=23253771&page=1) that seems relevant but couldn’t find a resolution. Apologies if I’m doing something silly again.

```javascript
const hypercore = require('hypercore')
const randomAccessIDB = require('random-access-idb')

const storage = (typeof window === 'undefined') ? './feed' : function () { return randomAccessIDB('hypercore-spike')('feed') }

const feed = hypercore(storage, {
  valueEncoding: 'utf-8',
  overwrite: true
})

feed.append('hello', function (error) {
  if (error) throw error

  feed.append('world', function (error) {
    if (error) throw error

    feed.get(0, console.log) // <-- Error: node not found
    feed.get(1, console.log)
  })
})
```

**Comment by mafintosh** [comment]
@aral 

```js
const browserStorage = randomAccessIDB('cool-stuff')
const feed = hypercore(filename => browserStorage(filename))
```

**Comment by aral** [comment]
@mafintosh Ah, gotcha, I was thinking about it all wrong. Thank you :)
