### ISSUE TITLE
valueEncoding: 'json' throws on read.

### ISSUE THREAD

**Issue by robertkowalski** [mafintosh/hypercore#178]
When I write JSON to a stream that is initialised with `valueEncoding: 'json'` it will throw on read.

Seems on read `JSON.parse` is called, so probably a JSON.stringify is missing on write?

```js

const test = hypercore('./candle-5m-btcusd-dataset', { valueEncoding: 'json' })
const stream = feed.createWriteStream()
stream.write([1,2,3])
feed.get(0, (err, res) => { console.log(err, res) })

SyntaxError: Unexpected token , in JSON at position 13
    at JSON.parse (<anonymous>)
    at Object.decodeJSON [as decode] (/Users/robert/bitfinex/hypercore-tutorial/node_modules/codecs/index.js:48:19)
    at Request._callback (/Users/robert/bitfinex/hypercore-tutorial/node_modules/hypercore/index.js:1315:17)
    at Request.callback (/Users/robert/bitfinex/hypercore-tutorial/node_modules/random-access-storage/index.js:161:8)
    at onread (/Users/robert/bitfinex/hypercore-tutorial/node_modules/random-access-file/index.js:80:31)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)

```

**Comment by mafintosh** [comment]
Hmm, I cannot reproduce this. Can you provide a full test case?
