### ISSUE TITLE
sodium-native breaks "npm install" with node 14.0

### ISSUE THREAD

**Issue by sergueyarellano** [mafintosh/hypercore#257]
Hi, this is breaking in my machine right now, 

If `sodium-universal` has `sodium-native` as an optional dependency, then, why the exit code 1?

Also, `sodium-native@3.0.1` installs fine with `node@14.0`

Is this the right place for this issue?

cheers
```
> sodium-native@2.4.9 install /Users/sam/.nvm/versions/node/v14.0.0/lib/node_modules/hypercore/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

libtool is required, but wasn't found on this system
./configure: line 5: ./configure: No such file or directory
/Users/sam/.nvm/versions/node/v14.0.0/lib/node_modules/hypercore/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/Users/sam/.nvm/versions/node/v14.0.0/lib/node_modules/hypercore/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by mafintosh** [comment]
We're in the process of updating to sodium@3 across the board.

**Comment by mafintosh** [comment]
(Right now it's using sodium 2)

**Comment by sergueyarellano** [comment]
oh, thanks for the answer!

All the best!

**Comment by mafintosh** [comment]
Fixed in Hypercore v9. See the CHANGELOG for other updates.
