### ISSUE TITLE
Cannot handle 3-way replication

### ISSUE THREAD

**Issue by mikeal** [mafintosh/hypercore#42]
In the case where you have more than 3 peers that are all replicating their own feed with **every** other peer you run into replication errors.

This may be a limitation of how this is implemented but it wasn't what I expected.

``` javascript
const hypercore = require('hypercore')
const through2 = require('through2')
const levelup = require('levelup')
const memdown = require('memdown')

function createFeed (id) {
  let db = levelup('.db' + id, {db: memdown})
  let core = hypercore(db)
  return core.createFeed()
}

function createThrough (id) {
  let ret = (chunk, enc, cb) => {
    console.log(id, 'chunk', chunk)
    cb(null, chunk)
  }
  return ret
}

const client1 = through2(createThrough('1'))
const client2 = through2(createThrough('2'))
const client3 = through2(createThrough('3'))

const feed1 = createFeed()
const feed2 = createFeed()
const feed3 = createFeed()

client2.pipe(feed1.replicate()).pipe(client2)
client3.pipe(feed1.replicate()).pipe(client3)

client1.pipe(feed2.replicate()).pipe(client1)
client3.pipe(feed2.replicate()).pipe(client3)

client1.pipe(feed3.replicate()).pipe(client1)
client2.pipe(feed3.replicate()).pipe(client2)

feed1.append(['hello', 'world'], function () {
  console.log('appended two blocks')
  console.log('key is', feed.key.toString('hex'))
})
```

Ends up with this output and error.

```
% node test.js                                                                                                   ~/git/hyperdoc
2 chunk <Buffer 3d 00 0a 20 be 2f 12 04 90 16 65 ca 46 1b ea 63 09 ae 75 25 55 18 41 8f 95 58 ad 30 88 83 47 bb 6b 45 9b 50 12 18 35 c8 5e 9c 94 b1 e0 31 0b c1 fb a9 ... >
2 chunk <Buffer 34 00 9f 7a ae 21 4f 34 dd 94 2b 04 47 65 a5 a5 ff db cb 15 fb 9c db b1 f4 66 df 8c 6a a2 b8 a2 b3 11 db 29 7d c5 f0 6a 92 41 1e b6 85 60 83 72 51 a5 ... >
3 chunk <Buffer 3d 00 0a 20 be 2f 12 04 90 16 65 ca 46 1b ea 63 09 ae 75 25 55 18 41 8f 95 58 ad 30 88 83 47 bb 6b 45 9b 50 12 18 b4 18 02 db ae 2c 08 76 43 c0 fa c8 ... >
3 chunk <Buffer 34 00 29 65 a4 73 c0 b4 10 a8 6c bc c1 f6 83 3d 3c 57 99 66 97 e6 9b d4 15 11 d8 bb ee 45 51 a0 09 42 b7 fa 22 09 a8 94 a4 ec 8e bd f2 e5 d1 5b 83 4b ... >
1 chunk <Buffer 3d 00 0a 20 a6 02 be 8f a4 0e 93 1f c0 2e 8c 10 97 27 6b 09 da 84 b8 2f 66 5b e0 fd b7 51 23 00 8a 55 97 32 12 18 23 26 13 f3 f4 fe 84 c8 7d d3 80 31 ... >
1 chunk <Buffer 34 00 43 60 3c 2b 74 bb ce cc 46 4f 4a 7d 2c 07 7e 0d b9 bf ed 92 a3 f7 6d 9f f0 ac 78 d0 9b 83 86 13 ef 3a d4 8f ac 7e e0 a9 09 23 8c 0d d9 83 45 ec ... >
3 chunk <Buffer 3d 00 0a 20 a6 02 be 8f a4 0e 93 1f c0 2e 8c 10 97 27 6b 09 da 84 b8 2f 66 5b e0 fd b7 51 23 00 8a 55 97 32 12 18 cd a8 7b 64 53 69 86 19 0a 0a af 7b ... >
3 chunk <Buffer 34 00 9f 82 58 c3 66 b3 e0 60 48 a1 0a dc e6 4b 55 2f d4 62 ef 24 82 a9 f1 bf 6f 95 c4 41 3b e5 87 10 5e 21 8a 52 07 15 cd e3 cd 9e 82 42 81 57 31 3a ... >
1 chunk <Buffer 3d 00 0a 20 45 6f 46 a7 ee b1 9a fb 8f 96 08 5a aa ca 29 35 ee ca 4e f2 6e 39 1f e0 22 f0 2c a2 21 45 bd 9a 12 18 43 15 5c d7 bc 7a ab 98 c5 ab 05 76 ... >
1 chunk <Buffer 34 00 51 4e bd a9 26 43 e8 2b 21 7a ba 6d e1 98 d6 67 d7 f9 e5 42 56 29 f7 8f 82 9a cf 2c 29 06 01 ee 6b 2d 00 9c 22 38 b1 d9 03 26 db 62 47 c1 d5 87 ... >
2 chunk <Buffer 3d 00 0a 20 45 6f 46 a7 ee b1 9a fb 8f 96 08 5a aa ca 29 35 ee ca 4e f2 6e 39 1f e0 22 f0 2c a2 21 45 bd 9a 12 18 21 64 6f 0d 6b 0a a2 83 da 23 b8 f1 ... >
2 chunk <Buffer 34 00 5b 35 f4 ae cc 52 a5 fc df b2 e1 2b db 03 80 18 2a 35 b6 1d 3f 3b 5b 50 54 2a 98 8b bb 3d 94 98 f3 c6 34 fc ad 58 a4 eb 67 85 f3 b7 ae 58 0f 7a ... >
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Remote echoed nonce
    at Protocol._open (/Users/mikeal/git/hyperdoc/node_modules/hypercore-protocol/index.js:489:80)
    at Protocol._onopen (/Users/mikeal/git/hyperdoc/node_modules/hypercore-protocol/index.js:416:10)
    at Protocol._parse (/Users/mikeal/git/hyperdoc/node_modules/hypercore-protocol/index.js:371:37)
    at parse (/Users/mikeal/git/hyperdoc/node_modules/hypercore-protocol/index.js:200:12)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at readableAddChunk (/Users/mikeal/git/hyperdoc/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at Readable.push (/Users/mikeal/git/hyperdoc/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at Transform.push (/Users/mikeal/git/hyperdoc/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at Decoder._push (/Users/mikeal/git/hyperdoc/node_modules/length-prefixed-stream/decode.js:28:8)
```

**Comment by mafintosh** [comment]
this should work. let me debug this for a second

**Comment by mafintosh** [comment]
ah i misunderstood your example. you need to only use a single replication stream for this use case (sorry this part could have better docs). let me cook you up an example

**Comment by mafintosh** [comment]
``` js
const hypercore = require('hypercore')
const levelup = require('levelup')
const memdown = require('memdown')

function createCore (id) {
  var db = levelup('.db' + id, {db: memdown})
  var core = hypercore(db)
  return core
}

var core1 = createCore('a')
var core2 = createCore('b')
var core3 = createCore('c')

var feed1 = core1.createFeed()
var feed2 = core2.createFeed()
var feed3 = core3.createFeed()

pipe(createReplicationStream(core1), createReplicationStream(core2))
pipe(createReplicationStream(core1), createReplicationStream(core3))

pipe(createReplicationStream(core2), createReplicationStream(core1))
pipe(createReplicationStream(core2), createReplicationStream(core3))

pipe(createReplicationStream(core3), createReplicationStream(core1))
pipe(createReplicationStream(core3), createReplicationStream(core2))

feed1.append(['hello', 'world'], function () {
  console.log('getting data from replicate ...')
  var replicatedFeed = core3.createFeed(feed1.key)
  replicatedFeed.get(0, console.log)
})

function createReplicationStream (core) {
  var stream = core.replicate()

  // you can reuse the feed instances if you want, this was easier in the example
  core.createFeed(feed1.key).replicate({stream: stream})
  core.createFeed(feed2.key).replicate({stream: stream})
  core.createFeed(feed3.key).replicate({stream: stream})

  return stream
}

function pipe (a, b) {
  a.pipe(b).pipe(a)
}
```

**Comment by pfrazee** [comment]
The diff:

```diff
2d1
< const through2 = require('through2')
6,9c5,8
< function createFeed (id) {
<   let db = levelup('.db' + id, {db: memdown})
<   let core = hypercore(db)
<   return core.createFeed()
---
> function createCore (id) {
>   var db = levelup('.db' + id, {db: memdown})
>   var core = hypercore(db)
>   return core
12,26c11,17
< function createThrough (id) {
<   let ret = (chunk, enc, cb) => {
<     console.log(id, 'chunk', chunk)
<     cb(null, chunk)
<   }
<   return ret
< }
< 
< const client1 = through2(createThrough('1'))
< const client2 = through2(createThrough('2'))
< const client3 = through2(createThrough('3'))
< 
< const feed1 = createFeed()
< const feed2 = createFeed()
< const feed3 = createFeed()
---
> var core1 = createCore('a')
> var core2 = createCore('b')
> var core3 = createCore('c')
> 
> var feed1 = core1.createFeed()
> var feed2 = core2.createFeed()
> var feed3 = core3.createFeed()
28,29c19,20
< client2.pipe(feed1.replicate()).pipe(client2)
< client3.pipe(feed1.replicate()).pipe(client3)
---
> pipe(createReplicationStream(core1), createReplicationStream(core2))
> pipe(createReplicationStream(core1), createReplicationStream(core3))
31,32c22,23
< client1.pipe(feed2.replicate()).pipe(client1)
< client3.pipe(feed2.replicate()).pipe(client3)
---
> pipe(createReplicationStream(core2), createReplicationStream(core1))
> pipe(createReplicationStream(core2), createReplicationStream(core3))
34,35c25,26
< client1.pipe(feed3.replicate()).pipe(client1)
< client2.pipe(feed3.replicate()).pipe(client2)
---
> pipe(createReplicationStream(core3), createReplicationStream(core1))
> pipe(createReplicationStream(core3), createReplicationStream(core2))
38,40c29,47
<   console.log('appended two blocks')
<   console.log('key is', feed.key.toString('hex'))
< })
\ No newline at end of file
---
>   console.log('getting data from replicate ...')
>   var replicatedFeed = core3.createFeed(feed1.key)
>   replicatedFeed.get(0, console.log)
> })
> 
> function createReplicationStream (core) {
>   var stream = core.replicate()
> 
>   // you can reuse the feed instances if you want, this was easier in the example
>   core.createFeed(feed1.key).replicate({stream: stream})
>   core.createFeed(feed2.key).replicate({stream: stream})
>   core.createFeed(feed3.key).replicate({stream: stream})
> 
>   return stream
> }
> 
> function pipe (a, b) {
>   a.pipe(b).pipe(a)
> }
```

**Comment by pfrazee** [comment]
@mafintosh so it looks like the main difference is, you need to create a "receiving" feed to replicate into. Right? So if there are 3 different cores, each with one feed, then there will be a total of 9 feed instances. 3 authoritative instances, and 6 receiving instances.

**Comment by mafintosh** [comment]
@pfrazee yea its simulating 3 different peers where each have a feed they own but all peers end up with the same state

**Comment by mikeal** [comment]
I'm just trying to think through how I would do this in a p2p network where I don't know the keys of all the feeds ahead of time.

**Comment by pfrazee** [comment]
Assuming you have a connection you trust, you can probably send the feed's pubkey over the connection as a pretext to sending the feed content.

 1. Send pubkey
 2. Recipient creates feed instance w/pubkey
 3. Both sides create replication stream and send over the connection

**Comment by mikeal** [comment]
Another related question, can I set the pubilc/private key? Every peer in my swarm already has a keypair and it would really simplify things if I could just re-use it for their feed.

**Comment by pfrazee** [comment]
Yes, I believe the usage is:

```js
core.createFeed(publicKey, { secretKey: secretKey })
```

Correct me if that's wrong, @mafintosh

**Comment by pfrazee** [comment]
Also need to double check that's the same kind of keypair

**Comment by mikeal** [comment]
Honestly, looking at `sodium`, which hyperlog is using, makes me want to move `killa-beez` over to it because it's much cleaner and probably smaller after browserify as well.

**Comment by substack** [comment]
[hyperdrive-multiwriter](https://github.com/substack/hyperdrive-multiwriter) can do what's being asked here without knowing all the keys in advance.
